[package]
name = "LLM-Man-Page"
version = "0.1.0"
edition = "2024"

[dependencies]
openai_api_rust = "0.1.9"
clap = { version = "4.5", features = ["derive"] } 
home = "0.5.11"
reqwest = {version = "0.12.20", features = ["blocking"]}
scraper = "0.23.1"
indicatif = "0.17.11"
